"use client";
import {useState} from "react"; import {Upload,FileText,Sparkles,ArrowRight,CheckCircle2} from "lucide-react";
export default function Home(){const [file,setFile]=useState<File|null>(null); const [drag,setDrag]=useState(false);
return <main className="min-h-screen overflow-hidden"><div className="mx-auto max-w-6xl px-5 py-8 md:px-8">
<header className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-purple-600/20 ring-1 ring-purple-400/30"><Sparkles className="text-purple-300"/></div><div><div className="font-bold tracking-wide">AKTEYNT AI</div><div className="text-xs text-zinc-500">MANGA TRANSLATOR</div></div></div><div className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs text-zinc-400">MVP • 0.1</div></header>
<section className="py-20 text-center"><div className="mx-auto mb-5 inline-flex items-center gap-2 rounded-full border border-purple-400/20 bg-purple-500/10 px-4 py-2 text-sm text-purple-200"><Sparkles size={15}/> AI-powered Uzbek translation</div><h1 className="text-5xl font-black tracking-tight md:text-7xl">Manga & Manhwa<br/><span className="bg-gradient-to-r from-purple-300 via-fuchsia-300 to-pink-300 bg-clip-text text-transparent">o‘zbek tilida.</span></h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-zinc-400 md:text-lg">PDF bobni yuklang. AI sahifalarni tahlil qiladi, matnni tarjima qiladi va manga ichidagi original yozuvlarni o‘zbekcha matn bilan almashtiradi.</p></section>
<section className="mx-auto max-w-3xl"><label onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);const f=e.dataTransfer.files[0];if(f?.type==="application/pdf")setFile(f)}} className={`block cursor-pointer rounded-3xl border-2 border-dashed p-10 text-center transition ${drag?"border-purple-400 bg-purple-500/10":"border-white/10 bg-white/[.025] hover:border-purple-500/40"}`}><input type="file" accept=".pdf,application/pdf" className="hidden" onChange={e=>setFile(e.target.files?.[0]??null)}/>{file?<div className="flex flex-col items-center"><CheckCircle2 size={42} className="mb-4 text-emerald-400"/><FileText size={22} className="mb-2 text-purple-300"/><p className="font-semibold">{file.name}</p><p className="mt-1 text-sm text-zinc-500">{(file.size/1024/1024).toFixed(2)} MB • PDF tayyor</p><button type="button" onClick={e=>{e.preventDefault();setFile(null)}} className="mt-5 text-sm text-purple-300 hover:text-white">Boshqa fayl tanlash</button></div>:<div><div className="mx-auto mb-5 grid h-16 w-16 place-items-center rounded-2xl bg-purple-500/10"><Upload className="text-purple-300"/></div><h2 className="text-xl font-bold">PDF faylni shu yerga tashlang</h2><p className="mt-2 text-sm text-zinc-500">yoki tanlash uchun bosing • 60–70 sahifagacha</p></div>}</label>
<div className="mt-5 flex justify-center"><button disabled={!file} className="flex items-center gap-2 rounded-2xl bg-purple-600 px-7 py-4 font-semibold shadow-lg shadow-purple-950/30 transition hover:bg-purple-500 disabled:cursor-not-allowed disabled:opacity-30">Tarjimani boshlash <ArrowRight size={18}/></button></div></section>
<section className="mx-auto grid max-w-4xl gap-4 py-20 md:grid-cols-3">{[["01","PDF","Bobni yuklash"],["02","AI","OCR + tarjima + joylash"],["03","PDF","Tayyor bobni olish"]].map(([n,t,d])=><div key={n} className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><div className="text-xs text-purple-300">{n}</div><div className="mt-3 font-bold">{t}</div><div className="mt-1 text-sm text-zinc-500">{d}</div></div>)}</section>
<footer className="border-t border-white/8 py-6 text-center text-xs text-zinc-600">Akteynt AI Manga Translator • Built for Uzbek manga readers</footer></div></main>}